version: '3.2'

services:

  varnish:
    image: million12/varnish
    depends_on:
      - nginx
    volumes:
      - ./varnish:/etc/varnish
    ports:
      - "8080:80"
    networks:
    - ckan-multi

  redis:
    image: redis:alpine
    restart: always
    networks:
    - ckan-multi

  nginx:
    depends_on:
    - ckan
    build:
      context: nginx
    restart: always
    networks:
    - ckan-multi

  jobs:
    depends_on:
    - jobs-db
    build:
      context: ckan
      args:
        CKAN_BRANCH: ${CKAN_BRANCH:-ckan-2.8.1}
        CKAN_REPO: ${CKAN_REPO:-ckan/ckan}
        POST_INSTALL: |
          install_standard_ckan_extension_github akariv/ckanext-cloudstorage ckanext-cloudstorage &&\
          install_standard_ckan_extension_github ckan/ckanext-scheming ckanext-scheming &&\
          ckan-pip install azure-storage==0.36.0 docopt ckanapi futures
        CKAN_INIT: |
          ckan-paster --plugin=ckanext-cloudstorage cloudstorage initdb -c "CKAN_CONFIG/production.ini"
        EXTRA_FILESYSTEM: fs
    command: [/ckan-entrypoint.sh, ckan-paster, --plugin=ckan, jobs, -c, /etc/ckan/production.ini, worker]
    restart: always
    volumes:
    - ./docker-compose/ckan-secrets.sh:/etc/ckan-conf/secrets/secrets.sh
    - ./docker-compose/ckan-conf-templates:/etc/ckan-conf/templates
    - ckan-data:/var/lib/ckan
    environment:
    - CKAN_STORAGE_PATH=/var/lib/ckan/data
    - CKAN_K8S_SECRETS=/etc/ckan-conf/secrets/secrets.sh
    - CKAN_K8S_TEMPLATES=/etc/ckan-conf/templates
    networks:
    - ckan-multi

  solr:
    build:
      context: solr
      args:
        SCHEMA_XML: ${SCHEMA_XML:-schema.xml}
    restart: always
    expose:
    - "8983"
    volumes:
    - solr:/opt/solr/server
    networks:
    - ckan-multi

  ckan:
    depends_on:
    - redis
    - solr
    - db
    - jobs
    - datastore-db
    build:
      context: ckan
      args:
        CKAN_BRANCH: ${CKAN_BRANCH:-ckan-2.8.1}
        CKAN_REPO: ${CKAN_REPO:-ckan/ckan}
        POST_INSTALL: |
          install_standard_ckan_extension_github akariv/ckanext-cloudstorage ckanext-cloudstorage &&\
          install_standard_ckan_extension_github ckan/ckanext-scheming ckanext-scheming &&\
          ckan-pip install azure-storage==0.36.0 docopt ckanapi futures
        CKAN_INIT: |
          ckan-paster --plugin=ckanext-cloudstorage cloudstorage initdb -c "CKAN_CONFIG/production.ini"
        EXTRA_FILESYSTEM: fs
    restart: always
    volumes:
    - ./docker-compose/ckan-secrets.sh:/etc/ckan-conf/secrets/secrets.sh
    - ./docker-compose/ckan-conf-templates:/etc/ckan-conf/templates
    - ckan-data:/var/lib/ckan
    environment:
    - CKAN_STORAGE_PATH=/var/lib/ckan/data
    - CKAN_K8S_SECRETS=/etc/ckan-conf/secrets/secrets.sh
    - CKAN_K8S_TEMPLATES=/etc/ckan-conf/templates
    - GUNICORN_WORKERS=2
    networks:
    - ckan-multi

  db:
    build:
      context: db
    restart: always
    expose:
    - "5432"
    environment:
    - POSTGRES_PASSWORD=123456
    volumes:
    - db:/var/lib/postgresql/data
    networks:
    - ckan-multi

  jobs-db:
    image: postgres
    restart: always
    expose:
    - "5432"
    environment:
    - POSTGRES_PASSWORD=123456
    volumes:
    - jobs-db:/var/lib/postgresql/data
    networks:
    - ckan-multi

  datastore-db:
    build:
      context: db
    restart: always
    expose:
    - "5432"
    environment:
    - POSTGRES_PASSWORD=123456
    - DATASTORE_RO_PASSWORD=123456
    - DATASTORE_RO_USER=readonly
    - DATASTORE_PUBLIC_RO_PASSWORD=123456
    volumes:
    - datastore-db:/var/lib/postgresql/data
    networks:
    - ckan-multi

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: $PWD/bkp/db
      o: bind
  ckan-data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/bkp/ckan-data
      o: bind
  jobs-db:
  datastore-db:
  solr:

networks:
  ckan-multi:
